# Generated by Django 3.1.3 on 2020-11-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(verbose_name='date_posted')),
            ],
        ),
    ]
